// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkM3MRRRCqPi-nZgvjrrDUGK5tmuRn0c',
    appId: '1:401693245016:web:b52dba430dcb9bf954142d',
    messagingSenderId: '401693245016',
    projectId: 'majoong-7ec07',
    authDomain: 'majoong-7ec07.firebaseapp.com',
    storageBucket: 'majoong-7ec07.appspot.com',
    measurementId: 'G-HQC774NQ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3JoEeIXOE8TYaPudJSYX0-oNJ60j6zs',
    appId: '1:401693245016:android:569240b13ea6642f54142d',
    messagingSenderId: '401693245016',
    projectId: 'majoong-7ec07',
    storageBucket: 'majoong-7ec07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMMS5rRFw1lbQXDP7TXk-lRWOFWpH9QY',
    appId: '1:401693245016:ios:c275f43e81288c6c54142d',
    messagingSenderId: '401693245016',
    projectId: 'majoong-7ec07',
    storageBucket: 'majoong-7ec07.appspot.com',
    iosClientId: '401693245016-e3damlifish7im8ftt2reb2kg9d7mqn0.apps.googleusercontent.com',
    iosBundleId: 'com.ssafy.majoong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMMS5rRFw1lbQXDP7TXk-lRWOFWpH9QY',
    appId: '1:401693245016:ios:c275f43e81288c6c54142d',
    messagingSenderId: '401693245016',
    projectId: 'majoong-7ec07',
    storageBucket: 'majoong-7ec07.appspot.com',
    iosClientId: '401693245016-e3damlifish7im8ftt2reb2kg9d7mqn0.apps.googleusercontent.com',
    iosBundleId: 'com.ssafy.majoong',
  );
}
