server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${MAJOONG_MYSQL_URL}
    username: ${MAJOONG_MYSQL_USERNAME}
    password: ${MAJOONG_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB

jwt:
  token:
    secret: ${JWT_SECRET_KEY}
  exclude-path: /user/login, /user/signup, /user/retoken, /user/phone, /user/phone/verify
  add-path: /user/**, /map/review

naver:
  access-key : ${NAVER_ACCESS_KEY}
  secret-key : ${NAVER_SERVICE_KEY}
  sms :
    service-id : ${SMS_SERVICE_ID}

springdoc:
  packages-to-scan: com.example.majoong
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger
    tags-sorter: method
    operations-sorter: method
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false