server:
  port: 8090

spring:
  datasource:
    url: ${MAJOONG_MYSQL_URL}
    username: ${MAJOONG_MYSQL_USERNAME}
    password: ${MAJOONG_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: true

jwt:
  token:
    secret: ${JWT_SECRET_KEY}
  exclude-path: /user/login, /user/signup, /user/retoken, /user/auth, /user/auth/verify
  add-path: /user/**

naver:
  access-key : ${NAVER_ACCESS_KEY}
  secret-key : ${NAVER_SERVICE_KEY}
  sms :
    service-id : ${SMS_SERVICE_ID}

